name: release

on:
  push:
    branches:
      - main
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Login to ghcr.io
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: arm64
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and publish container
        uses: docker/build-push-action@v4
        with:
          file: ./Containerfile
          context: .
          platforms: linux/arm64
          build-args: GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}
          tags: ghcr.io/cryi/z-way-container:latest,ghcr.io/cryi/z-way-container:${{ github.sha }}
          push: true
          provenance: false